services:
  kratos-migrate:
    networks:
      - yggdrasil

  kratos-selfservice-ui-node:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opensmh-ory-kratos-ui.rule=Host(`auth.ory-hydra.opensmh.shinyshoe.net`) && (PathPrefix(`/assets`) || PathPrefix(`/login`) || PathPrefix(`/logout`) || PathPrefix(`/registration`) || PathPrefix(`/settings`) || PathPrefix(`/recovery`) || PathPrefix(`/verification`) || PathPrefix(`/error`) || PathPrefix(`/consent`))"
      - "traefik.http.routers.opensmh-ory-kratos-ui.entrypoints=websecure"
      - "traefik.http.routers.opensmh-ory-kratos-ui.service=opensmh-ory-kratos-ui"
      - "traefik.http.routers.opensmh-ory-kratos-ui.tls=true"
      - "traefik.http.routers.opensmh-ory-kratos-ui.tls.certresolver=letsencrypt"
      - "traefik.http.services.opensmh-ory-kratos-ui.loadbalancer.server.port=4455"
    networks:
      - yggdrasil

  kratos:
    ports:
      - '4434:4434'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opensmh-ory-kratos-public.rule=Host(`auth.ory-hydra.opensmh.shinyshoe.net`)"
      - "traefik.http.routers.opensmh-ory-kratos-public.entrypoints=websecure"
      - "traefik.http.routers.opensmh-ory-kratos-public.service=opensmh-ory-kratos-public"
      - "traefik.http.routers.opensmh-ory-kratos-public.tls=true"
      - "traefik.http.routers.opensmh-ory-kratos-public.tls.certresolver=letsencrypt"
      - "traefik.http.services.opensmh-ory-kratos-public.loadbalancer.server.port=4433"
    networks:
      - yggdrasil

  hydra:
    ports:
      - "4445:4445"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opensmh-ory-hydra.rule=Host(`auth.ory-hydra.opensmh.shinyshoe.net`) && (PathPrefix(`/oauth2`) || PathPrefix(`/.well-known`) || PathPrefix(`/userinfo`))"
      - "traefik.http.routers.opensmh-ory-hydra.entrypoints=websecure"
      - "traefik.http.routers.opensmh-ory-hydra.service=opensmh-ory-hydra"
      - "traefik.http.routers.opensmh-ory-hydra.tls=true"
      - "traefik.http.routers.opensmh-ory-hydra.tls.certresolver=letsencrypt"
      - "traefik.http.services.opensmh-ory-hydra.loadbalancer.server.port=4444"
    networks:
      - yggdrasil
  
  hydra-migrate:
    networks:
      - yggdrasil
  app-ory:
    ports: !reset []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opensmh-ory-hydra-app.rule=Host(`ory-hydra.opensmh.shinyshoe.net`)"
      - "traefik.http.routers.opensmh-ory-hydra-app.entrypoints=websecure"
      - "traefik.http.routers.opensmh-ory-hydra-app.service=opensmh-ory-hydra-app"
      - "traefik.http.routers.opensmh-ory-hydra-app.tls=true"
      - "traefik.http.routers.opensmh-ory-hydra-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.opensmh-ory-hydra-app.loadbalancer.server.port=3000"
    networks:
      - yggdrasil

networks:
  yggdrasil:
    name: yggdrasil-heimdall
    external: true